In [72]:
nx = 5
gravit = 9.81
hinitl = 1.0
hinitr = 0.5
uinitl = 2.0
uinitr = 3.5
dx = 0.25
dt = 0.11

0.11

In [73]:
h     = zeros(Float64, nx);     u = zeros(Float64, nx);

In [74]:
for i in 1:nx
    h[i] , u[i] =  i < (nx ÷ 2) ? (hinitl, uinitl) : (hinitr, uinitr) 
end

In [75]:
@views h , @views u

([1.0, 0.5, 0.5, 0.5, 0.5], [2.0, 3.5, 3.5, 3.5, 3.5])

In [76]:
flux  = zeros(Float64, 2, nx-1)
fl    = zeros(Float64, 2)
fr    = zeros(Float64, 2)

2-element Vector{Float64}:
 0.0
 0.0

In [77]:
for i ∈ 1:nx-1
	hl = h[i]
	ul = u[i]
	ql = hl * ul
	hr = h[i+1]
	ur = u[i+1]
	qr = hr * ur
	fl[1] = hl * ul
	fl[2] = ul^2 * hl + 0.5*gravit * hl^2
	fr[1] = hr * ur
	fr[2] = ur^2 * hr + 0.5*gravit * hr^2
	flux[1, i] = 0.5 * (fl[1] + fr[1]) - 0.5 * dx / dt * (hr - hl)
	flux[2, i] = 0.5 * (fl[2] + fr[2]) - 0.5 * dx / dt * (qr - ql)
end

In [78]:
@views flux

2×4 Matrix{Float64}:
 2.44318  1.75     1.75     1.75
 8.41222  7.35125  7.35125  7.35125

In [79]:
diff(flux[1,:])

3-element Vector{Float64}:
 -0.6931818181818183
  0.0
  0.0

In [80]:
h[2:end-1] .-= dt ./ dx .* (diff(flux[1,:]))

3-element view(::Vector{Float64}, 2:4) with eltype Float64:
 0.805
 0.5
 0.5